package-lock.json, src/renderer/containers/Account/Account.scss, src/renderer/containers/Account/index.tsx
=> Account page ui updates

src/main/main.ts, src/renderer/components/FormElements/Button/Button.scss, src/renderer/components/Icon/index.tsx, src/renderer/components/Modal/Modal.scss, src/renderer/components/PageHeader/PageHeader.scss, src/renderer/components/PageTabs/PageTabs.scss, src/renderer/components/TrustBadge/TrustBadge.scss, src/renderer/containers/Connect/index.tsx, src/renderer/containers/Layout/Layout.scss, src/renderer/containers/Layout/index.tsx, src/renderer/containers/LeftMenu/LeftMenu.scss, src/renderer/containers/LeftMenu/index.tsx, src/renderer/containers/LeftSubmenu/LeftSubmenu.scss, src/renderer/containers/PageLayout/PageLayout.scss, src/renderer/containers/PageLayout/index.tsx, src/renderer/containers/PageTable/PageTable.scss, src/renderer/containers/TopNav/TopNav.scss, src/renderer/containers/TopNav/index.tsx, src/renderer/styles/colors.scss, src/renderer/styles/core.scss
I've updated the styling as close as possible to the new designs presented in #55 - it looks really amazing now. I've had however doubts with the colors and vars, there are too much colors in the design and we need to come up with some rules about coloring and color variables in the near future.
=> Update overall style guide/colors #55

package-lock.json, src/renderer/containers/Bank/EditBankModal/index.tsx, src/renderer/containers/LeftMenu/index.tsx, src/renderer/store/banks.ts, src/renderer/types/api.d.ts, src/renderer/types/entities/Bank.d.ts, src/renderer/types/entities/Bank.ts, src/renderer/types/entities/index.ts
Part of Issue #73 
Removed the redux implementations for now, since I will be making significant changes to the store on a separate branch
=> Pull/82 - Add nicknames modal for banks

src/renderer/containers/Account/AccountOverview/AccountOverview.scss, src/renderer/containers/Account/AccountOverview/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/104
=> 104 - Balance should be green

src/renderer/containers/Account/AccountOverview/AccountOverview.scss, src/renderer/containers/Account/AccountOverview/index.tsx, src/renderer/containers/App.tsx, src/renderer/hooks/useBooleanState.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/105
=> 105 - Signing key toggle for managed accounts

src/renderer/components/AccountNumberLink/AccountNumberLink.scss, src/renderer/components/AccountNumberLink/index.tsx, src/renderer/components/PageTable/index.tsx, src/renderer/containers/Account/AccountOverview/index.tsx, src/renderer/containers/Account/DeleteAccountModal/index.tsx, src/renderer/containers/Account/index.tsx, src/renderer/containers/Bank/BankAccounts/index.tsx, src/renderer/containers/Bank/BankBanks/index.tsx, src/renderer/containers/Bank/BankBlocks/index.tsx, src/renderer/containers/Bank/BankTransactions/index.tsx, src/renderer/containers/Bank/BankValidators/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/119
=> 119 - Linkable account numbers

src/renderer/components/FormElements/Select/index.tsx, src/renderer/containers/Account/SendPointsModal/SendPointsModalFields.tsx, src/renderer/containers/Account/SendPointsModal/index.tsx, src/renderer/hooks/useFormSelect.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/121
=> Creatable select and implemented in Send Point Modal

src/renderer/containers/LeftMenu/index.tsx, src/renderer/selectors/app.ts, src/renderer/selectors/index.ts
https://github.com/thenewboston-developers/Account-Manager/issues/144
=> 144 - point balance

src/renderer/containers/LeftMenu/LeftSubmenuItem/LeftSubmenuItem.scss, src/renderer/containers/LeftMenu/LeftSubmenuItem/index.tsx, src/renderer/containers/LeftMenu/LeftSubmenuItemStatus/LeftSubmenuItemStatus.scss, src/renderer/containers/LeftMenu/LeftSubmenuItemStatus/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/185
Label div added so ellipses don't butt up right against edge
=> Text overflow

src/renderer/containers/Bank/RemoveBankModal/index.tsx, src/renderer/containers/Bank/index.tsx, src/renderer/containers/Validator/RemoveValidatorModal/index.tsx, src/renderer/containers/Validator/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/100
=> 100 - remove bank/validator modal

src/renderer/containers/Validator/AddValidatorSigningKeyModal/index.tsx, src/renderer/containers/Validator/index.tsx
This was already done for the Bank, this adds the logic for the Validator as well
https://github.com/thenewboston-developers/Account-Manager/issues/69
=> 69 - Add/Remove NID Signing Key

src/renderer/containers/LeftMenu/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/191
=> 191 - commas to point balance

.eslintrc.json, src/renderer/components/Icon/index.tsx, src/renderer/containers/Account/CreateAccountModal/index.tsx, src/renderer/containers/Account/SendPointsModal/index.tsx, src/renderer/containers/App/EditTrustModal/index.tsx, src/renderer/containers/Bank/AddBankSigningKeyModal/index.tsx, src/renderer/containers/Bank/BankAccounts/BankAccounts.scss, src/renderer/containers/Bank/BankAccounts/index.tsx, src/renderer/containers/Bank/BankBanks/BankBanks.scss, src/renderer/containers/Bank/BankBanks/index.tsx, src/renderer/containers/Bank/BankValidators/BankValidators.scss, src/renderer/containers/Bank/BankValidators/index.tsx, src/renderer/containers/Bank/index.tsx, src/renderer/containers/Validator/AddValidatorSigningKeyModal/index.tsx, src/renderer/containers/Validator/ValidatorBanks/ValidatorBanks.scss, src/renderer/containers/Validator/ValidatorBanks/index.tsx, src/renderer/containers/Validator/ValidatorValidators/ValidatorValidators.scss, src/renderer/containers/Validator/ValidatorValidators/index.tsx, src/renderer/containers/Validator/index.tsx, src/renderer/utils/signing.ts
https://github.com/thenewboston-developers/Account-Manager/issues/151
https://github.com/thenewboston-developers/Account-Manager/issues/152
=> 151 152 - edit trust modal

src/renderer/components/Icon/index.tsx, src/renderer/constants/index.ts, src/renderer/containers/TopNav/index.tsx, src/renderer/dispatchers/app/index.ts, src/renderer/store/app/index.ts, src/renderer/store/app/managedAccounts.ts, src/renderer/store/app/managedBanks.ts, src/renderer/store/app/managedFriends.ts, src/renderer/store/app/managedValidators.ts, src/renderer/utils/store.ts
https://github.com/thenewboston-developers/Account-Manager/issues/209
=> 209 - reset state

src/renderer/containers/SendPointsModal/SendPointsModalFields.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/218
=> 218 - Display 'Friends' under the 'To' input

src/renderer/containers/Account/AccountOverview/index.tsx, src/renderer/store/app/index.ts, src/renderer/store/app/managedAccounts.ts, src/renderer/types/app.ts, src/renderer/types/index.ts, src/renderer/types/network.ts
https://github.com/thenewboston-developers/Account-Manager/issues/220
=> 220 - Update managed account balance

src/renderer/containers/Account/DeleteAccountModal/index.tsx, src/renderer/containers/Account/EditAccountNicknameModal/index.tsx, src/renderer/containers/Account/index.tsx, src/renderer/containers/Friend/DeleteFriendModal/index.tsx, src/renderer/containers/Friend/EditFriendNicknameModal/index.tsx, src/renderer/containers/Friend/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/228
=> 228 - Edit managed account nickname modal

src/renderer/components/PageTable/PageTable.scss, src/renderer/components/PageTabs/PageTabs.scss, src/renderer/components/PageTabs/index.tsx, src/renderer/components/PaginationSummary/PaginationSummary.scss, src/renderer/components/PaginationSummary/index.tsx, src/renderer/containers/Bank/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/94
=> Responsive scrolling fix

src/renderer/components/FormElements/Input/Input.scss, src/renderer/components/FormElements/Select/Select.scss
https://github.com/thenewboston-developers/Account-Manager/issues/206
=> 206 - input height to 30px

src/renderer/components/FormComponents/FormSelect/index.tsx, src/renderer/components/FormComponents/FormSelectDetailed/index.tsx, src/renderer/components/FormElements/Select/Select.scss, src/renderer/components/FormElements/Select/index.tsx, src/renderer/components/FormElements/SelectDetailed/SelectDetailed.scss, src/renderer/components/FormElements/SelectDetailed/index.tsx, src/renderer/hooks/useFormSelect.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/202
=> 202 - send points modal improvement

src/renderer/containers/Account/AccountOverview/index.tsx, src/renderer/containers/App.tsx, src/renderer/containers/SendPointsModal/SendPointsModalFields.tsx, src/renderer/containers/SendPointsModal/index.tsx, src/renderer/containers/TopNav/TopNavNotifications/TopNavNotifications.scss, src/renderer/containers/TopNav/TopNavNotifications/TopNavNotificationsMenu/TopNavNotificationsMenu.scss, src/renderer/containers/TopNav/TopNavNotifications/TopNavNotificationsMenu/index.tsx, src/renderer/containers/TopNav/TopNavNotifications/index.tsx, src/renderer/containers/TopNav/index.tsx, src/renderer/styles/colors.scss, src/renderer/utils/errors.ts
https://github.com/thenewboston-developers/Account-Manager/issues/233
=> 233 - Notifications

src/main/main.ts, src/renderer/components/Icon/index.tsx, src/renderer/containers/App.tsx, src/renderer/containers/EditTrustModal/index.tsx, src/renderer/containers/Layout/index.tsx, src/renderer/containers/TopNav/index.tsx, src/renderer/hooks/useNavigationalHistory.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/211
=> 211 - memoryRouter

src/renderer/utils/components.test.js
=> jest test for getCustomClassNames

src/renderer/utils/transactions.test.js
=> jest tests for transactions

src/renderer/containers/Validator/ValidatorBanks/index.tsx, src/renderer/containers/Validator/ValidatorValidators/index.tsx
=> Linkable account numbers

src/renderer/containers/Account/AccountTransactions/index.tsx, src/renderer/containers/Friend/FriendTransactions/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/252
**Note:**
The account numbers in those images in the issue were already updated, so I just audited the other remaining tables for any non-linked account numbers and updated these ones.
=> 252 - Account number link for Tx pages

src/renderer/containers/Account/AccountOverview/index.tsx
=> Updated format for Balance

package-lock.json, src/renderer/components/Modal/index.tsx, src/renderer/containers/Account/CreateAccountModal/index.tsx, src/renderer/containers/App.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/270
=> 270 - getStartedModal

src/renderer/components/FormElements/Button/Button.scss
https://github.com/thenewboston-developers/Account-Manager/issues/288
=> 288 - drop shadow on button

src/renderer/components/Tiles/TileAccountBalance/index.tsx, src/renderer/components/Tiles/TileAccountNumber/index.tsx, src/renderer/components/Tiles/TileSigningKey/index.tsx, src/renderer/containers/App.tsx, src/renderer/containers/LeftMenu/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/301
=> 301 - semantic updates

package-lock.json, src/renderer/containers/Account/CreateAccountModal/index.tsx, src/renderer/containers/Friend/FriendOverview/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/306
=> Closes #306 and fixed a wording issue

src/renderer/utils/address.test.js
=> Added jest test cases for parseAddressData and parseQueryParams

package-lock.json, src/renderer/containers/Account/AccountTransactions/index.tsx, src/renderer/containers/Friend/FriendTransactions/index.tsx, src/renderer/utils/address.test.js
Tests
https://github.com/thenewboston-developers/Account-Manager/issues/221
https://github.com/thenewboston-developers/Account-Manager/issues/222
https://github.com/thenewboston-developers/Account-Manager/issues/223
https://github.com/thenewboston-developers/Account-Manager/issues/224
https://github.com/thenewboston-developers/Account-Manager/issues/225
Features/bugs
https://github.com/thenewboston-developers/Account-Manager/issues/269
=> Added tests and Header text change on transaction table

src/renderer/containers/Account/CreateAccountModal/CreateAccountModalFields.tsx, src/renderer/containers/Account/CreateAccountModal/index.tsx
=> 307 - createNewAccountModal

src/renderer/containers/Friend/EditFriendNicknameModal/index.tsx
Added validation for: https://github.com/thenewboston-developers/Account-Manager/issues/318
=> Fixed bug: user should not get added with same nickname while editing nickname

src/renderer/containers/Friend/AddFriendModal/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/344 issue
=> Changed error message while validating existing friend

src/renderer/containers/Bank/AddBankModal/index.tsx, src/renderer/containers/Validator/AddValidatorModal/AddValidatorModalFields.tsx, src/renderer/containers/Validator/AddValidatorModal/index.tsx
https://github.com/thenewboston-developers/Account-Manager/issues/351
Same logic for Add Validator Modal will now apply as Add Bank Model
=> Changed validation message and logic for existing Validator

src/renderer/containers/SendPointsModal/index.tsx
Linked issue: https://github.com/thenewboston-developers/Account-Manager/issues/339
=> Integer validation on token send points modal

package-lock.json, src/renderer/components/DropdownMenuButton/index.tsx
=> fix: dropdown up/arrow key on disabled

src/renderer/containers/Bank/BankValidatorConfirmationServices/index.tsx
=> 348 - Format dates

src/renderer/components/Icon/index.tsx, src/renderer/components/Tiles/TileAccountNumber/TileAccountNumber.scss, src/renderer/components/Tiles/TileAccountNumber/index.tsx, src/renderer/components/Tiles/TileSigningKey/TileSigningKey.scss, src/renderer/components/Tiles/TileSigningKey/index.tsx
=> updated visibility icon and added copy icon for signing key

src/renderer/components/Tiles/TileKeyValueList/TileKeyValueList.scss, src/renderer/components/Tiles/TileValidatorSigningDetails/TileValidatorSigningDetails.scss, src/renderer/components/Tiles/TileValidatorSigningDetails/index.tsx, src/renderer/components/Tiles/index.tsx, src/renderer/containers/Validator/AddValidatorSigningKeysModal/index.tsx, src/renderer/containers/Validator/ValidatorOverview/ValidatorOverview.scss, src/renderer/containers/Validator/ValidatorOverview/index.tsx
=> #388 Tiles based styling for Validator Overview screen

src/renderer/containers/Validator/EditValidatorNicknameModal/index.tsx
This issue was reported on Validator Repo
video explaining the issue:
https://recordit.co/eOQt1G5Llh
https://github.com/thenewboston-developers/Account-Manager/issues/400
=> While Editing Validator nickname duplicate name should not be accepted

src/main/main.ts
fix for issue [#360](https://github.com/thenewboston-developers/Account-Manager/issues/360)
=> removed copy link from context menu (right click)

src/renderer/components/Tiles/TileDailyRate/TileDailyRate.scss, src/renderer/components/Tiles/TileDailyRate/index.tsx, src/renderer/components/Tiles/TilePrimaryAmount/index.tsx, src/renderer/components/Tiles/index.tsx, src/renderer/containers/Bank/BankOverview/index.tsx, src/renderer/containers/Validator/ValidatorOverview/index.tsx
=> moved daily rate to seperate panel

src/renderer/containers/Bank/AddBankModal/index.tsx, src/renderer/containers/Validator/AddValidatorModal/index.tsx
fix for issue [#395](https://github.com/thenewboston-developers/Account-Manager/issues/395)
=> Error messages improved

src/main/main.ts, src/renderer/components/Icon/index.tsx, src/renderer/components/Tiles/TileSigningKey/TileSigningKey.scss, src/renderer/components/Tiles/TileSigningKey/index.tsx
Be able to download signing key to a .txt file. The contents of the .txt file should be the signing key
=> Download signing key

src/renderer/components/Toast/Toast.scss
=> fixed text-icon alignment in success notification

src/renderer/components/Badge/Badge.scss, src/renderer/components/Toast/Toast.scss, src/renderer/containers/LeftMenu/LeftMenu.scss, src/renderer/containers/Notifications/Notifications.scss, src/renderer/styles/core.scss, src/renderer/styles/font.scss
Fix for #416 
Added Inter light even though it is not currently utilized, as it is utilized for the Website and may be useful here in the future.
Tested each change and no visual difference.
=> Allow for Inter fonts to use font weight, migrate usage

.github/ISSUE_TEMPLATE/bug_report.md, package-lock.json, src/renderer/containers/Account/DeleteAccountModal/index.tsx, src/renderer/containers/Account/index.tsx, src/renderer/containers/Friend/index.tsx, src/renderer/containers/LeftMenu/LeftMenu.scss, src/renderer/containers/LeftMenu/index.tsx, src/renderer/containers/PurchaseConfirmationServicesModal/index.tsx, src/renderer/containers/SendCoinsModal/SendCoinsModal.scss, src/renderer/containers/SendCoinsModal/SendCoinsModalFields/SendCoinsModalFields.scss, src/renderer/containers/SendCoinsModal/SendCoinsModalFields/index.tsx, src/renderer/containers/SendCoinsModal/index.tsx, src/renderer/selectors/app.ts, src/renderer/selectors/index.ts, src/renderer/utils/blocks.ts
=> Rename "points" to "coins"

src/renderer/containers/Account/EditAccountNicknameModal/index.tsx
Fixes #488
Behavior after this PR:
Acc No: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104
=> [My Accounts] Revalidate nickname when editing nickname

src/renderer/containers/Bank/EditBankNicknameModal/index.tsx
=> [Bank] Add validation for edit bank nickname

package.json, src/renderer/constants/form-validation.ts, src/renderer/containers/Account/CreateAccountModal/index.tsx, src/renderer/containers/Account/EditAccountNicknameModal/index.tsx, src/renderer/containers/Bank/AddBankModal/index.tsx, src/renderer/containers/Bank/AddBankSigningKeysModal/index.tsx, src/renderer/containers/Bank/EditBankNicknameModal/index.tsx, src/renderer/containers/Friend/AddFriendModal/index.tsx, src/renderer/containers/Friend/EditFriendNicknameModal/index.tsx, src/renderer/containers/Validator/AddValidatorModal/index.tsx, src/renderer/containers/Validator/EditValidatorNicknameModal/index.tsx
=> Move validation values to constants file

README.md
Add troubleshoot for the gyp: No Xcode or CLT version error during setup.
Closes #292
=> Update README.md with MacOS troubleshooting

src/renderer/containers/Notifications/NotificationsMenu/NotificationsMenu.scss
Resolves #439 
Account number: fb84a32a698a03dd327c4ce673f19fa0acf6e68cb50f143d5d7c080471bc4625
Made the padding to be consistent:
=> #439 - FIx Padding On Notifications Header

src/renderer/containers/SendCoinsModal/index.tsx
- added check to see if amount entered is over 999999999999999
- solves issue with amount being updated to 3
- solves potential issue with rounding up amount when over 999999999999999
=> [Issue-438]  points/coins amount too large issue

src/renderer/containers/Bank/AddBankModal/index.tsx, src/renderer/containers/Validator/AddValidatorModal/index.tsx
Resolves #482 
Account Number: 3b59cd93d7cb88fd55caaea77f07328b57cce7e3d1a14b13410291c698dccf2e
=> solves #482

src/renderer/containers/Notifications/index.tsx, src/renderer/utils/sort.ts
=> fixes issue #542

src/renderer/utils/clean.ts, src/renderer/utils/crawl.ts
=> 541 - handle crawl/clean when status is null

src/renderer/containers/Validator/ValidatorOverview/index.tsx, src/renderer/containers/Validator/index.tsx, src/renderer/hooks/useNetworkCleanFetcher.tsx, src/renderer/hooks/useNetworkCrawlFetcher.tsx, src/renderer/types/sockets.ts
=> 382 - clean and crawl for validators

jest.config.js, src/renderer/store/local/migrationFiles/00000/00000.test.ts, src/renderer/utils/transactions.test.ts
=> made .test.ts files understand absolute paths

src/renderer/components/PageTable/PageTable.scss, src/renderer/components/PaginatedTable/PaginatedTable.scss, src/renderer/styles/layout.scss
Fix: https://github.com/thenewboston-developers/Account-Manager/issues/590
**Screenshot:**
**Account Number:** `0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c`
=> Sticky toggle and paginated info

package.json
=> remove author from package json

package-lock.json, package.json, src/renderer/containers/Validator/AddValidatorSigningKeysModal/index.tsx, src/renderer/dispatchers/banks.ts, src/renderer/dispatchers/validators.ts, src/renderer/hooks/useCleanSockets.tsx, src/renderer/hooks/useCrawlSockets.tsx, src/renderer/hooks/useNetworkCleanFetcher.tsx, src/renderer/hooks/useNetworkCrawlFetcher.tsx
#617 
I replaced the try-catch block with the `Account.isValidPair` static method
=> Changes to the javascript-sdk-migration branch

src/main/main.ts
=> Fix window state

.github/workflows/test.yml
Fixes: https://github.com/thenewboston-developers/Account-Manager/issues/626
=> Remove node 12.x from test
